// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpqdrdjjoriikhlaqiwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwcWRyZGpqb3JpaWtobGFxaXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTM2MTcsImV4cCI6MjA1Nzk2OTYxN30.bt3dOs69YeF71uMkAf_x666RZXnHWQFUiSZ055oIoLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);