// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlkttjfiumuabkddrhme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsa3R0amZpdW11YWJrZGRyaG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDc3MjQsImV4cCI6MjA2MDQ4MzcyNH0.t7yh71DnTsxHYdOyGMTRGUB-sOSVNjguLWZeN68xptg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);